name: 'Build-Windows'

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'include/**'
      - 'examples/**'

jobs:
  build-windows:
    name: 'Build-Windows'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@master
      - name: 'Setup CMake'
        run: |
          mkdir build
          cd build
          cmake ..
        shell: cmd
      - name: 'Build'
        run: |
          cd build
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ConsoleLib.sln
        shell: cmd