name: 'Build'

on:
  push:
    branches:
      - 'master'

jobs:
  build-linux:
    name: 'Build-Linux'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: 'Setup CMake'
        run: |
          mkdir build
          cd build
          cmake ..
      - name: 'Build'
        run: |
          cd build/
          make
  build-windows:
    name: 'Build-Windows'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@master
      - name: 'Setup CMake'
        run: |
          mkdir build
          cd build
          cmake ..
          dir
      - name: 'Build'
        run: |
          cd build
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ConsoleLib.sln
