name: 'Documentation'

on:
  release:
    types:
      - created

jobs:
  build-docs:
    name: 'Build docs'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: 'Install doxygen'
        run: |
          sudo apt-get update
          sudo apt-get install doxygen -y
      - name: 'Build docs with doxygen'
        run: doxygen
      - name: 'Publish docs to gh-pages'
        run: |
          mv docs/ ../
          git checkout gh-pages
          rm -rf *
          mv ../docs/* .
          git config --local user.email ${{ secrets.COMMIT_MAIL }}
          git config --local user.name ${{ secrets.COMMIT_USER }}
          git add .
          git commit -m "New docs from commit $GITHUB_SHA"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
