name: 'Documentation'

on:
  push:
    branches:
      - 'master'

jobs:
  create-docs:
    name: 'Create docs'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: 'Install doxygen'
        run: |
          sudo apt-get update
          sudo apt-get install doxygen -y
      - name: 'Create docs with doxygen'
        run: doxygen
      - name: 'Move docs to gh-pages'
        run: |
          mv docs/ ../
          git checkout gh-pages
          rm -rf *
          mv ../docs/* .
          git config --local user.email "philmoeller10@gmail.com"
          git config --local user.name "TheDarkMen3000"
          git add .
          git commit -m "New docs from commit $GITHUB_SHA"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
